sudo: false
language: node_js
node_js:
# Current Long Term Stable (LTS) release
- "6"
# Pending LTS
- "8"
env:
  matrix:
  - GROUP=coverage
  - GROUP=packages
  - GROUP=lint
  - GROUP=flow
  - GROUP=conformance

cache:
  apt: true

before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: travis_retry npm run test:$GROUP
after_success:
  - 'if [[ $GROUP == coverage* ]]; then bash <(curl -s https://codecov.io/bash); fi'
